# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path                    = ["flake.lock", "Cargo.lock"]
SPDX-FileCopyrightText  = "2025 Ryan Cao <hello@ryanccn.dev>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path                    = ["tests/*/*.in/**/*"]
SPDX-FileCopyrightText  = "2025 Ryan Cao <hello@ryanccn.dev>"
SPDX-License-Identifier = "GPL-3.0-or-later"
