# SPDX-FileCopyrightText: 2025 Ryan Cao <hello@ryanccn.dev>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[formatting]
align_entries = true
column_width  = 120

[[rule]]
include     = ["tests/**/*.toml"]
schema.path = "https://raw.githubusercontent.com/assert-rs/snapbox/main/crates/trycmd/schema.json"
